server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/clinic

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/clinic}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  jackson:
    deserialization:
      fail-on-unknown-properties: true

service:
  mock: false

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /documentation